# Generated by Django 4.2.30 on 2026-06-07 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP')], max_length=16)),
                ('account_ref', models.CharField(help_text='AWS account alias/id or GCP project id.', max_length=180)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('credentials_hint', models.CharField(blank=True, max_length=160)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('ok', 'No Action')], max_length=16)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('resource_ref', models.CharField(blank=True, max_length=500)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('suggested_action', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ops.cloudaccount')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='ops.scanrun')),
            ],
            options={
                'ordering': ['severity', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('body_markdown', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=240)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('schedule_expression', models.CharField(blank=True, max_length=240)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=120)),
                ('target_ref', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['region', 'name'],
                'unique_together': {('account', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=240)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
                'unique_together': {('account', 'provider_id')},
            },
        ),
    ]
