# Generated by Django 4.2.30 on 2026-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='account_ref',
            field=models.CharField(blank=True, help_text='AWS account alias/id or GCP project id.', max_length=180),
        ),
    ]
