# Generated by Django 4.2.30 on 2026-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_alter_cloudaccount_account_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=8)),
                ('ai_model', models.CharField(default='gpt-5.4-mini-2026-03-17', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global settings',
                'verbose_name_plural': 'Global settings',
            },
        ),
    ]
