# Generated by Django 4.2.30 on 2026-06-08 03:16

import os

from django.db import migrations, models
import uuid


def seed_provider_from_env(apps, schema_editor):
    """Carry forward the legacy single-OpenAI configuration.

    Before this release the briefing model lived on GlobalSettings.ai_model and
    the key came from the OPENAI_API_KEY env var. Recreate that as the default
    AIProvider so existing installs keep generating AI briefings after upgrade.
    """
    AIProvider = apps.get_model("ops", "AIProvider")
    if AIProvider.objects.exists():
        return

    api_key = os.getenv("OPENAI_API_KEY", "").strip()
    if not api_key:
        return

    from ops.crypto import encrypt_text, secret_hint

    GlobalSettings = apps.get_model("ops", "GlobalSettings")
    settings_obj = GlobalSettings.objects.first()
    model = getattr(settings_obj, "ai_model", "") or os.getenv(
        "OPENAI_MODEL", "gpt-5.4-mini-2026-03-17"
    )

    AIProvider.objects.create(
        name="OpenAI (migrated)",
        provider="openai",
        model=model,
        encrypted_api_key=encrypt_text(api_key),
        api_key_hint=secret_hint(api_key),
        is_active=True,
        is_default=True,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_webhookendpoint_notificationdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)')], max_length=24)),
                ('model', models.CharField(help_text='Model id, e.g. gpt-5.4-mini, claude-opus-4-8, gemini-2.5-pro.', max_length=120)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('api_key_hint', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider',
                'verbose_name_plural': 'AI providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.RunPython(seed_provider_from_env, noop),
        migrations.RemoveField(
            model_name='globalsettings',
            name='ai_model',
        ),
    ]
