# Generated by Django 4.2.30 on 2026-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_aiprovider_remove_globalsettings_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='model',
            field=models.CharField(help_text='Model id, e.g. gpt-5.5, claude-opus-4-8, gemini-3.5-flash.', max_length=120),
        ),
    ]
