# Generated by Django 4.2.30 on 2026-06-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ops.models
import uuid


def assign_unique_webhook_tokens(apps, schema_editor):
    # AddField evaluates the callable default once, so every pre-existing
    # account would share one token. Re-issue a distinct token per row.
    CloudAccount = apps.get_model("ops", "CloudAccount")
    for account in CloudAccount.objects.all():
        account.webhook_token = ops.models.generate_webhook_token()
        account.save(update_fields=["webhook_token"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0006_alter_aiprovider_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='webhook_token',
            field=models.CharField(default=ops.models.generate_webhook_token, help_text='Shared secret for the inbound scan trigger webhook.', max_length=64),
        ),
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(choices=[(60, 'Every hour'), (360, 'Every 6 hours'), (720, 'Every 12 hours'), (1440, 'Every day'), (10080, 'Every week')], default=1440)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_schedule', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['account__name'],
            },
        ),
        migrations.CreateModel(
            name='RemediationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('generated', 'AI generated'), ('fallback', 'Template fallback'), ('failed', 'Failed')], max_length=16)),
                ('body_markdown', models.TextField(blank=True)),
                ('ai_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ops.finding')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            assign_unique_webhook_tokens,
            migrations.RunPython.noop,
        ),
    ]
