# Generated by Django 4.2.30 on 2026-06-10 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_cloudaccount_webhook_token_scanschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudaccount',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific options, e.g. gcp_billing_export_table.'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific options, e.g. notion_parent_page_id.'),
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='provider',
            field=models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('k8s', 'Kubernetes'), ('azure', 'Azure')], max_length=16),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='provider',
            field=models.CharField(choices=[('generic', 'Generic webhook'), ('slack', 'Slack incoming webhook'), ('notion', 'Notion page export')], default='generic', max_length=24),
        ),
        migrations.CreateModel(
            name='CustomRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(choices=[('resource', 'Resource'), ('schedule', 'Schedule')], max_length=16)),
                ('field_path', models.CharField(help_text='Field to inspect, e.g. name, region, state, metadata.timeout.', max_length=160)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains'), ('not_contains', 'Does not contain'), ('gt', 'Greater than (numeric)'), ('lt', 'Less than (numeric)'), ('regex', 'Matches regex')], max_length=16)),
                ('value', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('ok', 'No Action')], default='warning', max_length=16)),
                ('suggested_action', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Leave empty to apply the rule to every account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_rules', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
