# Generated by Django 4.2.30 on 2026-06-10 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_cloudaccount_options_webhookendpoint_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='github_issue_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='daily_report_enabled',
            field=models.BooleanField(default=False, help_text='Generate one combined briefing across all accounts every day.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='daily_report_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text='UTC hour (0-23) after which the scheduler generates the combined report.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='encrypted_github_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='github_repo',
            field=models.CharField(blank=True, help_text='owner/repo used when creating GitHub issues from findings.', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='github_token_hint',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='last_daily_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='receive_daily_report',
            field=models.BooleanField(default=False, help_text='Also send the combined daily report to this endpoint.'),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('scan', 'Account scan'), ('daily_report', 'Combined daily report')], max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='ops.cloudaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
