# Generated by Django 4.2.30 on 2026-06-10 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ops.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0009_finding_github_issue_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team')], default='free', max_length=16),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='plan_valid_until',
            field=models.DateField(blank=True, help_text='Paid plan expiry; after this date limits fall back to Free.', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('scan', 'Scan'), ('ai_call', 'AI call')], max_length=16)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'kind'],
                'unique_together': {('date', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=ops.models.generate_webhook_token, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('is_global_admin', models.BooleanField(default=False)),
                ('account_roles', models.JSONField(blank=True, default=dict, help_text='Mapping of cloud account id -> role granted on acceptance.')),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitation', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
